#################################
# General setup
#################################
language: python

sudo: false

matrix:
  include:
  - python: "2.7"
  - python: "3.3"
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"

notifications:
  email: false

#################################
# Build Lifecycle
#################################
install:
  # Start the install of everything
  - pip install --upgrade pip wheel
  - pip install -r requirements-dev.txt

script:
  - python -m pytest -v pyerf
